#! /usr/bin/env python
import sys
import tasklib

if __name__ == '__main__':
    tasks = set()
    
    startdir = '.'
    if len(sys.argv) == 2:
        startdir = sys.argv[1]

    print 'Looking for tasks (*.txt) under %s' % (startdir,)

    tasks = tasklib.gather_tasks(startdir)

    print '%d tasks:' % (len(tasks),)
    for task in tasks:
        print '\t', task
