#! /usr/bin/env python
import sys
import tasklib

if __name__ == '__main__':
    tasks = set()
    
    startdir = '.'
    if len(sys.argv) == 2:
        startdir = sys.argv[1]

    print 'Looking for tasks (*.txt) under %s' % (startdir,)

    tasks = tasklib.gather_tasks(startdir)
    tasks = list(tasks)

    def mycmp(a, b):
        return cmp(a.summary, b.summary)
    tasks.sort(mycmp)

    print '%d tasks:' % (len(tasks),)
    for task in tasks:
        print '\t', task

    owners = set()
    for task in tasks:
        owners.add(task.owner)

    tags = {}
    for task in tasks:
        for tag in task.tags:
            n = tags.get(tag, 0)
            n += 1
            tags[tag] = n

    tags_by_name = list(tags.keys())
    tags_by_name.sort()
    print '%d tags:' % (len(tags_by_name),)
    for tag in tags_by_name:
        print "\t%s - %d" % (tag, tags[tag])

    owners = list(owners)
    owners.sort()
    print ",".join(owners)
